# **NUMPY**
- core of the numpy package is ndarray object
- n-dimensional array of homogenos data types
- np arrays have fixed size at creation, unlike python lists which grow dynamically
- used for large mathematical operations


In [1]:
import numpy as np



In [2]:
a = np.array([[1,2,3,4],[5,6]])

C:\Users\naine\AppData\Local\Temp\ipykernel_14676\2416776178.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a = np.array([[1,2,3,4],[5,6]])


In [3]:
type(a)

numpy.ndarray

In [4]:
len(a)

2

In [5]:
a.shape

(2,)

In [6]:
a

array([list([1, 2, 3, 4]), list([5, 6])], dtype=object)

In [7]:
a.ndim


1

In [8]:
a2 = np.array([[1,2,3],[4,5,6]])

In [9]:
a2.ndim

2

In [10]:
a2.shape

(2, 3)

In [11]:
ar1 = np.array([1,2,3,4])
ar2 = np.array([5,6,7,8])

In [12]:
arry = np.concatenate((ar1,ar2))

In [13]:
arry

array([1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
arry = np.concatenate((ar1,ar2), axis =0)

In [15]:
arry

array([1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
#join arrray using stack function
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])


In [17]:
ar = np.stack((a1,a2),axis=1)

In [18]:
ar

array([[1, 4],
       [2, 5],
       [3, 6]])

In [19]:
a1 = np.array([4,6,9,2,3,7,8,1,3])

In [20]:
ar3 = np.arange(10)

In [21]:
ar4 = np.arange(40)
ar4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

# lists are slow and numpy is fast
- numpy uses fixed types
- bytes is converted into int32/int16 type
- lists requires more space than numpy, computer reads numpy faster than lists
- no type-checking while typing
- numpy has contiguous memory
- numpy has SIMD -  single instruction multi data vector processing
- effective cache utilization

In [22]:
s1 = np.array([1,2,3,4,5],dtype='int16')


# Applications of NUMPY
- MATLAB REPLACEMENT
- plotting
- backend
- machine learning


In [23]:
s1.ndim


1

In [24]:
s1.shape

(5,)

In [25]:
s1.dtype

dtype('int16')

In [26]:
 s1.itemsize

2

In [29]:
s2 = np.array([1,2,3,4,5,6,7,8,9])


In [33]:
#get a specific element
s2[0:3]


array([1, 2, 3])

In [34]:
s2[4:6]

array([5, 6])